
/* Vegas Happy Hours PWA – generated by tools/build.py */
function startApp(DATA){
"use strict";

var DAYN=['Mon','Tue','Wed','Thu','Fri','Sat','Sun'];
var STRIP=[36.1147,-115.1728];
var $=function(id){return document.getElementById(id)};
function esc(s){return String(s==null?'':s).replace(/[&<>"']/g,function(c){return {'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]})}
function present(s){return s&&String(s).trim()&&String(s).trim().toLowerCase()!=='not listed'}
function safeUrl(u){return /^https?:\/\//i.test(u||'')?u:null}

var map=L.map('map',{zoomControl:true}).setView(STRIP,11);
L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:19,attribution:'&copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors'}).addTo(map);
var cluster=L.markerClusterGroup({maxClusterRadius:45,showCoverageOnHover:false,spiderfyOnMaxZoom:true,disableClusteringAtZoom:18});
map.addLayer(cluster);
var leg=L.control({position:'bottomleft'});
leg.onAdd=function(){var d=L.DomUtil.create('div','legend');L.DomEvent.disableClickPropagation(d);d.onclick=function(){d.classList.toggle('open')};d.innerHTML='<div class="lt">ⓘ Legend</div><div><span class="pin hh"></span>Happy hour</div><div><span class="pin br"></span>Brunch</div><div><span class="pin ln"></span>Late night / reverse HH</div><div><span class="pin" style="background:linear-gradient(90deg,#2563eb 50%,#7c3aed 50%)"></span>Split colors = on several lists</div><div><span class="pin hh approx"></span>Dashed orange ring = approximate location</div><div><span class="pin hh ikring"></span>Teal ring = on inKind</div><div><span class="pin" style="background:#10b981"></span>You</div>';return d};
leg.addTo(map);

var user=null,userMarker=null,markers={},activeId=null;
var state={mode:'all',q:'',zip:'',days:{},now:false,minRating:0,exactOnly:false,bothOnly:false,ikOnly:false};
var KS=['hh','br','ln'],COL={hh:'#2563eb',br:'#db2777',ln:'#7c3aed'};
function has(v){return KS.filter(function(k){return !!v[k]})}
function cats(v){return KS.filter(function(k){return v[k]&&(state.mode==='all'||state.mode===k)})}
function kindOf(v){var c=cats(v);if(!c.length)c=has(v);return c.length>1?'multi':c[0]}
function pinBg(v){var c=cats(v);if(!c.length)c=has(v);if(c.length===1)return COL[c[0]];
  var st=[],w=100/c.length;c.forEach(function(k,i){st.push(COL[k]+' '+(i*w).toFixed(1)+'%',COL[k]+' '+((i+1)*w).toFixed(1)+'%')});return 'linear-gradient(90deg,'+st.join(',')+')'}
function iconFor(v){var k=kindOf(v);return L.divIcon({className:'',html:'<div class="pin '+k+(v.approx?' approx':'')+(v.ik&&v.ik.s==='Yes'?' ikring':'')+'" data-cats="'+cats(v).join(' ')+'" style="background:'+pinBg(v)+'"></div>',iconSize:[16,16],iconAnchor:[8,8],popupAnchor:[0,-8]})}
var CATN={hh:'🍸 Happy hour',br:'🥂 Brunch',ln:'🌙 Late night / reverse happy hour'};
var EMO={hh:'🍸 ',br:'🥂 ',ln:'🌙 '},BADGE={hh:'HH',br:'Brunch',ln:'Late'};
DATA.forEach(function(v,i){v.id=i;
  if(v.lat!=null){
    var m=L.marker([v.lat,v.lng],{icon:iconFor(v),title:v.name});
    m.bindPopup(function(){return popupHtml(v)},{maxWidth:300});
    m.on('click',function(){setActive(v.id,false)});
    markers[v.id]=m;
  }
});

function dirUrl(v){
  var dest=v.approx?(v.name+', '+v.addr):(v.lat+','+v.lng);
  return 'https://www.google.com/maps/dir/?api=1&destination='+encodeURIComponent(dest);
}
function dist(v){
  if(!user||v.lat==null)return null;
  var R=3958.8,p=Math.PI/180,dLa=(v.lat-user[0])*p,dLo=(v.lng-user[1])*p;
  var a=Math.sin(dLa/2)*Math.sin(dLa/2)+Math.cos(user[0]*p)*Math.cos(v.lat*p)*Math.sin(dLo/2)*Math.sin(dLo/2);
  return 2*R*Math.asin(Math.sqrt(a));
}
function fmtDist(d,v){return d==null?'':((v.approx?'~':'')+(d<0.1?'<0.1':d.toFixed(1))+' mi')}
function srcTag(c){
  if(c.conf==='editorial')return '<p class="warn">⚠ UNVERIFIED: this brunch listing comes from an editorial roundup / aggregator only and was not confirmed on the venue\'s own page. Check before you go.</p>';
  if(c.conf==='snippet')return '<p class="note">Partially verified: from a search-result snippet of the venue/resort page (page itself not opened).</p>';
  if(c.conf==='official')return '<p class="note">Verified on the venue\'s own page.</p>';
  return '';
}
function lnTag(c){
  var f=c.conf||'',h='';
  if(/^UNVERIFIED/.test(f))h+='<p class="warn">⚠ UNVERIFIED: this late-night deal comes from an aggregator/editorial listing only and was not confirmed on the venue\'s own page. Call ahead.</p>';
  else if(/^PARTIALLY/.test(f))h+='<p class="note">Partially verified ('+esc(f)+').</p>';
  else if(/^VERIFIED/.test(f))h+='<p class="note">Verified on the venue/resort official page.</p>';
  var fl=[];['CONFLICTING','OUTDATED','POSSIBLY OUTDATED','LOW CONFIDENCE','INDUSTRY ONLY'].forEach(function(x){if(f.indexOf(x)>=0&&!(x==='OUTDATED'&&f.indexOf('POSSIBLY OUTDATED')>=0))fl.push(x)});
  if(fl.length)h+='<p class="warn">⚠ '+esc(fl.join(' · '))+' — see notes.</p>';
  return h;
}
function secHtml(v,k){
  var c=v[k];if(!c)return '';
  var h='<div class="sec '+k+'"><h4>'+CATN[k]+(k==='br'&&c.bname?' — '+esc(c.bname):'')+(k==='ln'&&c.lname?' — '+esc(c.lname):'')+'</h4>';
  h+='<p><span class="k">Days:</span> '+esc(c.days)+'<br><span class="k">Times:</span> '+esc(c.times)+'</p>';
  if(k==='hh'||k==='ln'){if(present(c.deals))h+='<p><span class="k">'+(k==='ln'?'Late-night deal':'Deals')+':</span> '+esc(c.deals)+'</p>'}
  else{h+='<p><span class="k">Brunch specials:</span> '+esc(c.spec)+'</p>'}
  h+='<p><span class="k">Items &amp; prices:</span> '+esc(c.items)+'</p>';
  if(k==='br')h+=srcTag(c);
  if(k==='ln')h+=lnTag(c);
  var u=safeUrl(c.url);if(u)h+='<p style="margin:2px 0"><a href="'+esc(u)+'" target="_blank" rel="noopener" style="font-size:12px">source</a></p>';
  if(present(c.notes))h+='<p class="note"><span class="k">Confidence / notes:</span> '+esc(c.notes)+'</p>';
  return h+'</div>';
}
function ikHtml(v){
  var i=v.ik;
  if(!i)return '<p class="note">inKind: not found in inKind\'s Las Vegas list (checked Oct 9, 2026) — not proof it isn\'t on inKind.</p>';
  var u=safeUrl(i.url),h='<div class="iksec"><b>'+(i.s==='Yes'?'<span class="ik" style="margin:0">inKind</span> On inKind':'<span class="ik unc" style="margin:0">inKind?</span> Possibly on inKind (unclear)')+'</b>';
  if(present(i.note))h+='<div class="note" style="margin-top:3px">'+esc(i.note)+'</div>';
  if(u)h+='<a class="ikbtn" href="'+esc(u)+'" target="_blank" rel="noopener">Open on inKind ➜</a>';
  return h+'</div>';
}
function ikBadge(v){
  if(!v.ik)return '';
  var u=safeUrl(v.ik.url),cls=v.ik.s==='Yes'?'ik':'ik unc',lab=v.ik.s==='Yes'?'inKind':'inKind?';
  return u?'<a class="'+cls+'" href="'+esc(u)+'" target="_blank" rel="noopener" title="'+(v.ik.s==='Yes'?'On inKind – open inKind page':'Possibly on inKind (unclear match)')+'" onclick="event.stopPropagation()">'+lab+'</a>':'<span class="'+cls+'">'+lab+'</span>';
}
function popupHtml(v){
  var h='<div class="pop"><h3>'+esc(v.name)+'</h3>';
  if(present(v.loc))h+='<div class="note">'+esc(v.loc)+'</div>';
  h+='<p>📍 '+esc(v.addr)+'</p>';
  if(v.approx)h+='<p class="warn">⚠ Approximate pin ('+esc(v.q)+'). This is not a verified street location.</p>';
  var d=dist(v);if(d!=null)h+='<p><span class="k">Distance:</span> '+fmtDist(d,v)+'</p>';
  var ks=KS.slice(),act=cats(v);
  ks.sort(function(a,b){return (act.indexOf(b)>=0)-(act.indexOf(a)>=0)});
  var hv=has(v);if(v.ik&&v.ik.s==='Yes')h=h.replace('<h3>'+esc(v.name)+'</h3>','<h3>'+esc(v.name)+ikBadge(v)+'</h3>');
  if(hv.length>1)h+='<p class="note"><b>On '+hv.length+' lists: '+hv.map(function(k){return CATN[k].replace(/^\S+ /,'')}).join(', ')+'.</b></p>';
  ks.forEach(function(k){h+=secHtml(v,k)});
  h+=ikHtml(v);
  h+='<p><span class="k">Rating:</span> '+(v.rating!=null?('★ '+v.rating+(v.src?' ('+esc(v.src)+')':'')+(v.reviews?' · '+Number(v.reviews).toLocaleString()+' reviews':'')):'not found')+'</p>';
  h+='<a class="dir" href="'+dirUrl(v)+'" target="_blank" rel="noopener">Directions ➜</a>';
  return h+'</div>';
}

/* ---- happening now (Las Vegas time) ---- */
var NOW_OVERRIDE=null;
function vegasNow(){
  if(NOW_OVERRIDE)return NOW_OVERRIDE;
  try{
    var parts=new Intl.DateTimeFormat('en-US',{timeZone:'America/Los_Angeles',weekday:'short',hour:'numeric',minute:'numeric',hour12:false}).formatToParts(new Date());
    var o={};parts.forEach(function(p){o[p.type]=p.value});
    var d=({Mon:0,Tue:1,Wed:2,Thu:3,Fri:4,Sat:5,Sun:6})[o.weekday];
    return {day:d,min:(parseInt(o.hour,10)%24)*60+parseInt(o.minute,10)};
  }catch(e){var n=new Date();return {day:(n.getDay()+6)%7,min:n.getHours()*60+n.getMinutes()}}
}
function isNowC(c){
  if(!c||!c.sch)return false;
  var n=vegasNow(),prev=(n.day+6)%7,i,w;
  /* windows are [start,end] minutes from midnight of the listed day; values >1440 run past midnight
     (e.g. "Sun-Thu 12 AM-3 AM" late-night windows are stored as [1440,1620] on the night they belong to) */
  var t=c.sch[n.day]||[];
  for(i=0;i<t.length;i++){w=t[i];if(n.min>=w[0]&&n.min<w[1])return true}
  var y=c.sch[prev]||[],m2=n.min+1440;
  for(i=0;i<y.length;i++){w=y[i];if(m2>=w[0]&&m2<w[1])return true}
  return false;
}
function isNow(v){return cats(v).some(function(k){return isNowC(v[k])})}

/* ---- filters ---- */
var zips={};DATA.forEach(function(v){if(v.zip)zips[v.zip]=(zips[v.zip]||0)+1});
Object.keys(zips).sort().forEach(function(z){var o=document.createElement('option');o.value=z;o.textContent=z+' ('+zips[z]+')';$('zip').appendChild(o)});
DAYN.forEach(function(d,i){var b=document.createElement('button');b.className='chip';b.textContent=d;b.onclick=function(){state.days[i]=!state.days[i];b.classList.toggle('on',!!state.days[i]);refresh()};$('days').appendChild(b)});
$('q').addEventListener('input',function(){state.q=this.value.trim().toLowerCase();refresh()});
$('zip').onchange=function(){state.zip=this.value;refresh()};
$('rating').onchange=function(){state.minRating=parseFloat(this.value);refresh()};
$('exactOnly').onchange=function(){state.exactOnly=this.checked;refresh()};
$('bothOnly').onchange=function(){state.bothOnly=this.checked;refresh()};
$('ikOnly').onchange=function(){state.ikOnly=this.checked;refresh()};
Array.prototype.forEach.call($('mode').children,function(b){b.onclick=function(){state.mode=b.getAttribute('data-mode');syncMode();refresh()}});
function syncMode(){Array.prototype.forEach.call($('mode').children,function(b){b.classList.toggle('on',b.getAttribute('data-mode')===state.mode)})}
$('now').onclick=function(){state.now=!state.now;this.classList.toggle('on',state.now);refresh()};
$('reset').onclick=function(){state={mode:'all',q:'',zip:'',days:{},now:false,minRating:0,exactOnly:false,bothOnly:false,ikOnly:false};$('ikOnly').checked=false;syncMode();$('q').value='';$('zip').value='';$('rating').value='0';$('exactOnly').checked=false;$('bothOnly').checked=false;$('now').classList.remove('on');Array.prototype.forEach.call($('days').children,function(b){b.classList.remove('on')});refresh();fitAll()};
$('viewtoggle').onclick=function(){document.body.classList.toggle('listmode');setTimeout(function(){map.invalidateSize()},50)};

function passes(v){
  var act=cats(v);if(!act.length)return false;
  if(state.bothOnly&&has(v).length<2)return false;
  if(state.ikOnly&&!(v.ik&&v.ik.s==='Yes'))return false;
  if(state.zip&&v.zip!==state.zip)return false;
  if(state.exactOnly&&v.approx)return false;
  if(state.minRating>0&&!(v.rating!=null&&v.rating>=state.minRating))return false;
  var anyDay=false,k;for(k in state.days)if(state.days[k])anyDay=true;
  if(anyDay){var ok=false;for(k in state.days)if(state.days[k])act.forEach(function(c){if(v[c].ds.indexOf(+k)>=0)ok=true});if(!ok)return false}
  if(state.now&&!isNow(v))return false;
  if(state.q){var hay=v.name+' '+v.loc+' '+v.addr+' '+v.zip;
    act.forEach(function(c){var x=v[c];hay+=' '+(c==='br'?x.spec+' '+(x.bname||''):x.deals)+' '+(x.lname||'')+' '+x.items+' '+x.days+' '+x.times});
    hay=hay.toLowerCase();
    var toks=state.q.split(/\s+/);for(var i=0;i<toks.length;i++)if(hay.indexOf(toks[i])<0)return false}
  return true;
}
var visible=[];
function refresh(){
  visible=DATA.filter(passes);
  cluster.clearLayers();
  var ms=[];visible.forEach(function(v){var m=markers[v.id];if(m){m.setIcon(iconFor(v));ms.push(m)}});
  cluster.addLayers(ms);
  renderList();
}
function renderList(){
  var arr=visible.slice();
  if(user)arr.sort(function(a,b){var x=dist(a),y=dist(b);return (x==null?1e9:x)-(y==null?1e9:y)});
  else arr.sort(function(a,b){return a.name.localeCompare(b.name)});
  var nowSet=state.now;
  var h='',max=400;
  arr.slice(0,max).forEach(function(v){
    var d=dist(v);
    h+='<div class="item'+(v.id===activeId?' active':'')+'" data-id="'+v.id+'">'+
      (d!=null?'<span class="d">'+fmtDist(d,v)+'</span>':'')+
      '<div class="n">'+esc(v.name)+ikBadge(v)+cats(v).map(function(k){return '<span class="badge '+k+'">'+BADGE[k]+'</span>'}).join('')+(v.approx?'<span class="tag" title="'+esc(v.q)+'">approx</span>':'')+(isNow(v)?'<span class="tag now">now</span>':'')+(cats(v).indexOf('br')>=0&&v.br.conf==='editorial'?'<span class="tag warn" title="Editorial/aggregator-only brunch listing">unverified</span>':'')+(cats(v).indexOf('br')>=0&&v.br.conf==='snippet'?'<span class="tag" title="From a search snippet of the venue page">snippet-only</span>':'')+(cats(v).indexOf('ln')>=0&&/^UNVERIFIED/.test(v.ln.conf)?'<span class="tag warn" title="Aggregator/editorial-only late-night listing">late: unverified</span>':'')+'</div>'+
      cats(v).map(function(k){var x=v[k];return '<div class="m c-'+k+'">'+EMO[k]+esc(x.days)+' · '+esc(x.times)+'</div>'}).join('')+
      '<div class="m">'+(v.rating!=null?'★ '+v.rating+' · ':'')+esc(v.addr)+'</div></div>';
  });
  if(arr.length>max)h+='<div class="item" style="cursor:default;color:#555">Showing first '+max+' of '+arr.length+' — refine filters to see more.</div>';
  if(!arr.length)h='<div class="item" style="cursor:default">No venues match these filters.</div>';
  $('list').innerHTML=h;
  var unm=visible.filter(function(v){return v.lat==null}).length;
  $('status').textContent=visible.length+' of '+DATA.length+' venues ('+({hh:'happy hour',br:'brunch',ln:'late night',all:'all categories'})[state.mode]+')'+(user?' · sorted nearest first':' · sorted A–Z (use location for nearest-first)')+(unm?' · '+unm+' unmapped':'');
}
$('list').addEventListener('click',function(e){
  var el=e.target.closest('.item[data-id]');if(!el)return;
  focusVenue(+el.getAttribute('data-id'));
});
function setActive(id,scroll){
  activeId=id;
  Array.prototype.forEach.call($('list').querySelectorAll('.item'),function(el){
    var on=+el.getAttribute('data-id')===id;el.classList.toggle('active',on);
    if(on&&scroll)el.scrollIntoView({block:'nearest'});
  });
}
function focusVenue(id){
  var v=DATA[id],m=markers[id];setActive(id,false);
  if(!m){toast('This venue could not be placed on the map.');return}
  document.body.classList.remove('listmode');
  setTimeout(function(){
    map.invalidateSize();
    cluster.zoomToShowLayer(m,function(){map.setView(m.getLatLng(),Math.max(map.getZoom(),16));m.openPopup()});
  },60);
}
function toast(msg,ms){var t=$('toast');t.textContent=msg;t.style.display='block';clearTimeout(toast._t);toast._t=setTimeout(function(){t.style.display='none'},ms||5000)}
function fitAll(){
  var pts=DATA.filter(function(v){return v.lat!=null}).map(function(v){return [v.lat,v.lng]});
  if(pts.length)map.fitBounds(L.latLngBounds(pts).pad(0.05));
  map.setView(STRIP,11);
}

/* ---- geolocation ---- */
$('loc').onclick=function(){
  if(!navigator.geolocation){toast('Geolocation is not supported by this browser. Showing the Las Vegas Strip.');map.setView(STRIP,13);return}
  var btn=this;btn.disabled=true;btn.textContent='Locating…';
  navigator.geolocation.getCurrentPosition(function(pos){
    btn.disabled=false;btn.textContent='📍 Update my location';
    user=[pos.coords.latitude,pos.coords.longitude];
    if(userMarker)map.removeLayer(userMarker);
    userMarker=L.marker(user,{icon:L.divIcon({className:'',html:'<div class="you"></div>',iconSize:[18,18],iconAnchor:[9,9]}),zIndexOffset:1000,title:'You are here'}).addTo(map).bindPopup('<b>You are here</b>');
    renderList();
    var near=visible.filter(function(v){return v.lat!=null}).sort(function(a,b){return dist(a)-dist(b)}).slice(0,10);
    var b=L.latLngBounds([user]);near.forEach(function(v){b.extend([v.lat,v.lng])});
    map.fitBounds(b.pad(0.2),{maxZoom:15});
    userMarker.openPopup();
    var far=near.length&&dist(near[0])>50;
    toast(far?'Your location is far from Las Vegas (nearest venue '+Math.round(dist(near[0]))+' mi away).':'Showing nearest venues first.',4000);
  },function(err){
    btn.disabled=false;btn.textContent='📍 Use my location';
    var msg=err&&err.code===1?'Location permission denied.':(err&&err.code===3?'Location request timed out.':'Could not determine your location.');
    toast(msg+' Showing the Las Vegas Strip instead.',6000);
    map.setView(STRIP,13);
  },{enableHighAccuracy:true,timeout:15000,maximumAge:60000});
};

var nHH=DATA.filter(function(v){return v.hh}).length,nBR=DATA.filter(function(v){return v.br}).length,nLN=DATA.filter(function(v){return v.ln}).length,nBoth=DATA.filter(function(v){return has(v).length>1}).length;
$('sub').textContent=DATA.length+' venues · '+nHH+' happy hour · '+nBR+' brunch · '+nLN+' late night · '+nBoth+' on 2+ lists · '+DATA.filter(function(v){return v.approx}).length+' approximate pins (dashed orange) · '+DATA.filter(function(v){return v.ik&&v.ik.s==='Yes'}).length+' on inKind (teal ring) · late-night windows after midnight belong to the previous evening';
$('mode').children[0].textContent='🍸 HH ('+nHH+')';$('mode').children[1].textContent='🥂 Brunch ('+nBR+')';$('mode').children[2].textContent='🌙 Late ('+nLN+')';$('mode').children[3].textContent='All ('+DATA.length+')';
refresh();
setInterval(function(){if(state.now)refresh()},60000);
window.__vhh={nIK:DATA.filter(function(v){return v.ik&&v.ik.s==='Yes'}).length,count:DATA.length,nHH:nHH,nBR:nBR,nLN:nLN,nBoth:nBoth,setNow:function(d,m){NOW_OVERRIDE=(d==null?null:{day:d,min:m});refresh()},nowCount:function(){return DATA.filter(function(v){return isNow(v)}).length},isNowC:function(c){return isNowC(c)},markers:function(){return Object.keys(markers).length},visible:function(){return visible.length},onMap:function(){return cluster.getLayers().length},mode:function(){return state.mode}};
}

(function(){
  function fail(e){var s=document.getElementById('status');if(s)s.textContent='Could not load venue data ('+(e&&e.message||e)+'). Check your connection and reload.';}
  fetch('data.json',{cache:'no-cache'}).then(function(r){if(!r.ok)throw new Error('HTTP '+r.status);return r.json()}).then(startApp).catch(function(e){
    // offline fallback: try the SW cache explicitly
    if(window.caches){caches.match('data.json',{ignoreSearch:true}).then(function(r){return r?r.json().then(startApp):fail(e)}).catch(fail)}else fail(e);
  });
  if('serviceWorker' in navigator){window.addEventListener('load',function(){navigator.serviceWorker.register('sw.js').catch(function(e){console.warn('SW registration failed',e)})})}
  // mobile filters toggle
  var ft=document.getElementById('filtertoggle');
  if(ft)ft.onclick=function(){document.body.classList.toggle('filtersopen');ft.classList.toggle('on')};
  // iOS "Add to Home Screen" hint
  var ua=navigator.userAgent||'',isIOS=/iPad|iPhone|iPod/.test(ua)||(navigator.platform==='MacIntel'&&navigator.maxTouchPoints>1);
  var standalone=window.navigator.standalone===true||(window.matchMedia&&matchMedia('(display-mode: standalone)').matches);
  var hint=document.getElementById('a2hs');
  var dismissed=false;try{dismissed=localStorage.getItem('a2hsDismissed')==='1'}catch(e){}
  if(hint&&isIOS&&!standalone&&!dismissed){hint.style.display='block'}
  var hx=document.getElementById('a2hsClose');
  if(hx)hx.onclick=function(){hint.style.display='none';try{localStorage.setItem('a2hsDismissed','1')}catch(e){}};
  // Android/Chrome install prompt
  var deferred=null,ib=document.getElementById('installBtn');
  window.addEventListener('beforeinstallprompt',function(e){e.preventDefault();deferred=e;if(ib)ib.style.display='inline-block'});
  if(ib)ib.onclick=function(){if(!deferred)return;deferred.prompt();deferred.userChoice.finally(function(){deferred=null;ib.style.display='none'})};
  window.addEventListener('appinstalled',function(){if(ib)ib.style.display='none'});
})();
