"""Build the PWA from the map template.
Usage:  python3 tools/build.py [--from-html /workspace/vegas_hh_map_inkind.html]
- index.html / app.js are generated from /workspace/vhh/template_inkind.html (if present) or app_src/template.html.
- data.json: if --from-html given, extracted from that single-file map; otherwise kept as-is.
- Bumps the service-worker cache version automatically (content hash).
"""
import json, re, sys, os, hashlib, shutil
ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
os.chdir(ROOT)
TPL_SRC = '/workspace/vhh/template_inkind.html'
os.makedirs('app_src', exist_ok=True)
if os.path.exists(TPL_SRC): shutil.copy(TPL_SRC, 'app_src/template.html')
tpl = open('app_src/template.html').read()

if '--from-html' in sys.argv:
    src = sys.argv[sys.argv.index('--from-html') + 1]
    t = open(src).read()
    i = tpl.index('__DATA__'); pre, post = tpl[:i], tpl[i+8:]
    assert t.startswith(pre) and t.endswith(post), 'html does not match template'
    recs = json.loads(t[len(pre):len(t)-len(post)].replace('<\\/', '</'))
    json.dump(recs, open('data.json', 'w'), ensure_ascii=False, separators=(',', ':'))

def rep(s, a, b, cnt=1):
    assert s.count(a) == cnt, (a, s.count(a)); return s.replace(a, b)

head, rest = tpl.split('<script src="https://unpkg.com/leaflet@1.9.4/dist/leaflet.js"></script>', 1)
js = rest.split('<script>', 1)[1].rsplit('</script>', 1)[0]

# ---------- app.js ----------
js = rep(js, '(function(){\n"use strict";', '/* Vegas Happy Hours PWA – generated by tools/build.py */\nfunction startApp(DATA){\n"use strict";')
js = rep(js, "var DATA=JSON.parse(document.getElementById('data').textContent);", '')
js = rep(js, "leg.onAdd=function(){var d=L.DomUtil.create('div','legend');d.innerHTML='<div>", "leg.onAdd=function(){var d=L.DomUtil.create('div','legend');L.DomEvent.disableClickPropagation(d);d.onclick=function(){d.classList.toggle('open')};d.innerHTML='<div class=\"lt\">ⓘ Legend</div><div>")
js = js.rstrip()
assert js.endswith('})();')
js = js[:-5] + '}\n' + r'''
(function(){
  function fail(e){var s=document.getElementById('status');if(s)s.textContent='Could not load venue data ('+(e&&e.message||e)+'). Check your connection and reload.';}
  fetch('data.json',{cache:'no-cache'}).then(function(r){if(!r.ok)throw new Error('HTTP '+r.status);return r.json()}).then(startApp).catch(function(e){
    // offline fallback: try the SW cache explicitly
    if(window.caches){caches.match('data.json',{ignoreSearch:true}).then(function(r){return r?r.json().then(startApp):fail(e)}).catch(fail)}else fail(e);
  });
  if('serviceWorker' in navigator){window.addEventListener('load',function(){navigator.serviceWorker.register('sw.js').catch(function(e){console.warn('SW registration failed',e)})})}
  // mobile filters toggle
  var ft=document.getElementById('filtertoggle');
  if(ft)ft.onclick=function(){document.body.classList.toggle('filtersopen');ft.classList.toggle('on')};
  // iOS "Add to Home Screen" hint
  var ua=navigator.userAgent||'',isIOS=/iPad|iPhone|iPod/.test(ua)||(navigator.platform==='MacIntel'&&navigator.maxTouchPoints>1);
  var standalone=window.navigator.standalone===true||(window.matchMedia&&matchMedia('(display-mode: standalone)').matches);
  var hint=document.getElementById('a2hs');
  var dismissed=false;try{dismissed=localStorage.getItem('a2hsDismissed')==='1'}catch(e){}
  if(hint&&isIOS&&!standalone&&!dismissed){hint.style.display='block'}
  var hx=document.getElementById('a2hsClose');
  if(hx)hx.onclick=function(){hint.style.display='none';try{localStorage.setItem('a2hsDismissed','1')}catch(e){}};
  // Android/Chrome install prompt
  var deferred=null,ib=document.getElementById('installBtn');
  window.addEventListener('beforeinstallprompt',function(e){e.preventDefault();deferred=e;if(ib)ib.style.display='inline-block'});
  if(ib)ib.onclick=function(){if(!deferred)return;deferred.prompt();deferred.userChoice.finally(function(){deferred=null;ib.style.display='none'})};
  window.addEventListener('appinstalled',function(){if(ib)ib.style.display='none'});
})();
'''
open('app.js', 'w').write(js)

# ---------- index.html ----------
h = head
h = rep(h, '<meta name="viewport" content="width=device-width, initial-scale=1, viewport-fit=cover">',
'''<meta name="viewport" content="width=device-width, initial-scale=1, viewport-fit=cover">
<meta name="theme-color" content="#1f2937">
<meta name="description" content="Las Vegas happy hours, brunch, late-night specials and inKind restaurants on a map, sorted nearest-first.">
<meta name="mobile-web-app-capable" content="yes">
<meta name="apple-mobile-web-app-capable" content="yes">
<meta name="apple-mobile-web-app-status-bar-style" content="black-translucent">
<meta name="apple-mobile-web-app-title" content="VegasHH">
<link rel="manifest" href="manifest.webmanifest">
<link rel="icon" type="image/png" sizes="192x192" href="icons/icon-192.png">
<link rel="apple-touch-icon" sizes="180x180" href="icons/apple-touch-icon.png">''')
h = rep(h, '<title>Las Vegas Happy Hour, Brunch &amp; Late-Night Map (with inKind)</title>', '<title>Vegas Happy Hours</title>')
h = rep(h, 'https://unpkg.com/leaflet@1.9.4/dist/leaflet.css', 'vendor/leaflet.css')
h = rep(h, 'https://unpkg.com/leaflet.markercluster@1.5.3/dist/MarkerCluster.css', 'vendor/MarkerCluster.css')
h = rep(h, 'https://unpkg.com/leaflet.markercluster@1.5.3/dist/MarkerCluster.Default.css', 'vendor/MarkerCluster.Default.css')
css = '''
header{padding-top:calc(10px + env(safe-area-inset-top))}
#filtertoggle,#installBtn{display:none}
#a2hs{display:none;position:absolute;left:8px;right:8px;bottom:calc(10px + env(safe-area-inset-bottom));z-index:1100;background:#111827f0;color:#fff;border-radius:12px;padding:10px 34px 10px 12px;font-size:13px;box-shadow:0 4px 16px rgba(0,0,0,.4)}
#a2hs b{color:#fcd34d}
#a2hs .shr{display:inline-block;border:1px solid #fff8;border-radius:4px;padding:0 4px;font-size:12px}
#a2hsClose{position:absolute;right:4px;top:4px;background:none;border:0;color:#fff;font-size:18px;padding:4px 8px}
@media (max-width:760px){
 header{padding:calc(6px + env(safe-area-inset-top)) 10px 4px}
 header h1{font-size:15px}
 #filtertoggle{display:inline-block}
 #controls{max-height:none;overflow:visible}
 #controls .opt{display:none}
 body.filtersopen #controls .opt{display:flex}
 body.filtersopen #controls{max-height:55vh;overflow-y:auto}
 #side{height:48%}
 #list{padding-bottom:env(safe-area-inset-bottom)}
 button,select,input[type=search]{min-height:36px}
 #controls .row button{padding:6px 8px;font-size:13px}
 .legend .lt{display:block;font-weight:600;cursor:pointer}
 .legend>div:not(.lt){display:none}
 .legend.open>div{display:block}
}
.legend .lt{display:none}
</style>'''
h = rep(h, '</style>', css)
h = rep(h, '<div class="row" id="days"></div>', '<div class="row opt" id="days"></div>')
h = rep(h, '''   <div class="row">
     <button id="now"''', '''   <div class="row opt">
     <button id="now"''')
h = rep(h, '<button id="viewtoggle">☰ List / 🗺 Map</button>', '<button id="viewtoggle">☰ List / 🗺 Map</button>\n     <button id="filtertoggle">⚙ Filters</button>\n     <button id="installBtn">⬇ Install app</button>')
h = rep(h, '<div id="toast"></div></div>', '''<div id="toast"></div>
  <div id="a2hs" role="note"><button id="a2hsClose" aria-label="Dismiss">×</button>📲 <b>Install this app:</b> tap <span class="shr">Share ⬆</span> in Safari, then <b>Add to Home Screen</b>.</div></div>''')
h = h.rstrip() + '\n<script src="vendor/leaflet.js"></script>\n<script src="vendor/leaflet.markercluster.js"></script>\n<script src="app.js"></script>\n</body></html>\n'
open('index.html', 'w').write(h)

# ---------- service worker version bump ----------
files = ['index.html', 'app.js', 'data.json', 'manifest.webmanifest']
hsh = hashlib.sha256(b''.join(open(f, 'rb').read() for f in files)).hexdigest()[:10]
sw = open('sw.js').read()
sw = re.sub(r"const VERSION = '[^']*';", f"const VERSION = 'v-{hsh}';", sw)
open('sw.js', 'w').write(sw)
print('built; cache version', hsh, '; venues', len(json.load(open('data.json'))))
